# Generated by Django 4.0.5 on 2022-08-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=500)),
                ('task', models.CharField(default='', max_length=5000)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
